import 'package:focal_project/model/hotel_model.dart';
import 'package:get/get.dart';

class HotelServices {
  static List<HotelModel> get allHotels => [
        HotelModel(
          id: "1",
          name: "hotel_services.hotel_1_name".tr,
          location: "hotel_services.hotel_1_location".tr,
          pricePerNight: 480,
          oldPricePerNight: 550,
          rating: 4.8,
          reviewsCount: 320,
          imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_1_description".tr,
          category: "categories.hotel_services".tr,
          isFavorite: false,
          latitude: 34.0522,
          longitude: -118.2437,
        ),
        HotelModel(
          id: "2",
          name: "hotel_services.hotel_2_name".tr,
          location: "hotel_services.hotel_2_location".tr,
          pricePerNight: 190,
          oldPricePerNight: 230,
          rating: 4.5,
          reviewsCount: 180,
          imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_2_description".tr,
          category: "categories.hotel_services".tr,
          isFavorite: true,
          latitude: 32.7157,
          longitude: -117.1611,
        ),
        HotelModel(
          id: "3",
          name: "hotel_services.hotel_3_name".tr,
          location: "hotel_services.hotel_3_location".tr,
          pricePerNight: 270,
          oldPricePerNight: 320,
          rating: 4.6,
          reviewsCount: 410,
          imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_3_description".tr,
          category: "categories.villas".tr,
          isFavorite: false,
          latitude: 21.3069,
          longitude: -157.8583,
        ),
        HotelModel(
          id: "4",
          name: "hotel_services.hotel_4_name".tr,
          location: "hotel_services.hotel_4_location".tr,
          pricePerNight: 320,
          oldPricePerNight: 400,
          rating: 4.2,
          reviewsCount: 95,
          imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_4_description".tr,
          category: "categories.apartments".tr,
          isFavorite: false,
          latitude: 32.7314,
          longitude: -117.1460,
        ),
        HotelModel(
          id: "5",
          name: "hotel_services.hotel_5_name".tr,
          location: "hotel_services.hotel_5_location".tr,
          pricePerNight: 120,
          oldPricePerNight: 199,
          rating: 4.4,
          reviewsCount: 532,
          imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_5_description".tr,
          category: "categories.hotel_services".tr,
          isFavorite: true,
          latitude: 34.0195,
          longitude: -118.4912,
        ),
        HotelModel(
          id: "6",
          name: "hotel_services.hotel_6_name".tr,
          location: "hotel_services.hotel_6_location".tr,
          pricePerNight: 550,
          oldPricePerNight: 620,
          rating: 4.9,
          reviewsCount: 128,
          imageUrl: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_6_description".tr,
          category: "categories.villas".tr,
          isFavorite: false,
          latitude: 34.0259,
          longitude: -118.7798,
        ),
        HotelModel(
          id: "7",
          name: "hotel_services.hotel_7_name".tr,
          location: "hotel_services.hotel_7_location".tr,
          pricePerNight: 310,
          rating: 4.7,
          reviewsCount: 245,
          imageUrl: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_7_description".tr,
          category: "categories.hotel_services".tr,
          isFavorite: false,
          latitude: 37.7749,
          longitude: -122.4194,
        ),
        HotelModel(
          id: "8",
          name: "hotel_services.hotel_8_name".tr,
          location: "hotel_services.hotel_8_location".tr,
          pricePerNight: 290,
          oldPricePerNight: 340,
          rating: 4.3,
          reviewsCount: 160,
          imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_8_description".tr,
          category: "categories.villas".tr,
          isFavorite: false,
          latitude: 25.7617,
          longitude: -80.1918,
        ),
        HotelModel(
          id: "9",
          name: "hotel_services.hotel_9_name".tr,
          location: "hotel_services.hotel_9_location".tr,
          pricePerNight: 210,
          rating: 4.1,
          reviewsCount: 88,
          imageUrl: "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_9_description".tr,
          category: "categories.apartments".tr,
          isFavorite: false,
          latitude: 47.6062,
          longitude: -122.3321,
        ),
        HotelModel(
          id: "10",
          name: "hotel_services.hotel_10_name".tr,
          location: "hotel_services.hotel_10_location".tr,
          pricePerNight: 410,
          oldPricePerNight: 480,
          rating: 4.8,
          reviewsCount: 302,
          imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80",
          description: "hotel_services.hotel_10_description".tr,
          category: "categories.hotel_services".tr,
          isFavorite: false,
          latitude: 39.1911,
          longitude: -106.8175,
        ),
      ];
}