import 'package:focal_project/model/hotel_model.dart';

class HotelServices {
  static List<HotelModel> allHotels = [
    HotelModel(
      id: "1",
      name: "The Horizon Retreat",
      location: "Los Angeles, CA",
      pricePerNight: 480,
      oldPricePerNight: 550,
      rating: 4.8,
      reviewsCount: 320,
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
      description: "Experience world-class luxury at The Horizon Retreat with panoramic city views, infinity pool, and premium spa facilities.",
      category: "Hotels",
      isFavorite: false,
    ),
    HotelModel(
      id: "2",
      name: "Opal Grove Inn",
      location: "San Diego, CA",
      pricePerNight: 190,
      oldPricePerNight: 230,
      rating: 4.5,
      reviewsCount: 180,
      imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
      description: "Cozy stay near the ocean with top amenities, complimentary breakfast, and easy beach access.",
      category: "Hotels",
      isFavorite: true,
    ),
    HotelModel(
      id: "3",
      name: "Serenity Sands Resort",
      location: "Honolulu, HI",
      pricePerNight: 270,
      oldPricePerNight: 320,
      rating: 4.6,
      reviewsCount: 410,
      imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      description: "A tropical beachfront paradise offering luxury suites, private balconies, and oceanfront dining.",
      category: "Villas",
      isFavorite: false,
    ),
    HotelModel(
      id: "4",
      name: "Elysian Ocean Suites",
      location: "San Diego, CA",
      pricePerNight: 320,
      oldPricePerNight: 400,
      rating: 4.2,
      reviewsCount: 95,
      imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
      description: "Modern luxury suites equipped with private jacuzzis, high-speed Wi-Fi, and personalized concierge service.",
      category: "Apartments",
      isFavorite: false,
    ),
    HotelModel(
      id: "5",
      name: "Tranquil Shores Resort",
      location: "Santa Monica, CA",
      pricePerNight: 120,
      oldPricePerNight: 199,
      rating: 4.4,
      reviewsCount: 532,
      imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
      description: "Relaxing stay close to the pier featuring stylish interior designs and lush garden spaces.",
      category: "Hotels",
      isFavorite: true,
    ),
    HotelModel(
      id: "6",
      name: "Oceanic Vista Villa",
      location: "Malibu, CA",
      pricePerNight: 550,
      oldPricePerNight: 620,
      rating: 4.9,
      reviewsCount: 128,
      imageUrl: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
      description: "Exclusive cliffside villa providing direct ocean views, private infinity pool, and personalized chef services.",
      category: "Villas",
      isFavorite: false,
    ),
    HotelModel(
      id: "7",
      name: "Grand Palace Hotel",
      location: "San Francisco, CA",
      pricePerNight: 310,
      rating: 4.7,
      reviewsCount: 245,
      imageUrl: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80",
      description: "Historic architecture meets modern comfort in downtown San Francisco, ideal for both business and leisure.",
      category: "Hotels",
      isFavorite: false,
    ),
    HotelModel(
      id: "8",
      name: "Sunset Bay Resort",
      location: "Miami, FL",
      pricePerNight: 290,
      oldPricePerNight: 340,
      rating: 4.3,
      reviewsCount: 160,
      imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      description: "Vibrant beachside resort with private beach access, rooftop cocktail lounge, and live entertainment.",
      category: "Villas",
      isFavorite: false,
    ),
    HotelModel(
      id: "9",
      name: "Azure Heights Suites",
      location: "Seattle, WA",
      pricePerNight: 210,
      rating: 4.1,
      reviewsCount: 88,
      imageUrl: "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=800&q=80",
      description: "Sleek metropolitan apartments with skyline views, fully equipped kitchens, and fitness center.",
      category: "Apartments",
      isFavorite: false,
    ),
    HotelModel(
      id: "10",
      name: "Mountain Edge Lodge",
      location: "Aspen, CO",
      pricePerNight: 410,
      oldPricePerNight: 480,
      rating: 4.8,
      reviewsCount: 302,
      imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80",
      description: "Cozy alpine lodge with ski-in/ski-out access, outdoor heated pools, and stone fireplace lounges.",
      category: "Hotels",
      isFavorite: false,
    ),
  ];
}